"""Cost table: everything the pipeline did, from out/runs.jsonl.

    .venv/Scripts/python pipeline/cost_table.py          -> markdown to stdout + docs/costs.md
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Comfy Cloud developer pricing 2026-09-18: RTX 6000 Pro $3.49/h. Local electricity:
# AR residential tariff is heavily subsidised; we price local energy at $0.10/kWh as a stand-in.
USD_PER_KWH = 0.10


def rows():
    for line in (ROOT / "out" / "runs.jsonl").read_text(encoding="utf-8").splitlines():
        yield json.loads(line)


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    agg = defaultdict(lambda: {"n": 0, "cached": 0, "errors": 0, "ms": 0, "wh": 0.0, "usd": 0.0, "gpu_s": 0.0})
    for r in rows():
        stage = r.get("stage")
        if stage == "qa_gate":
            continue
        backend = r.get("backend") or ("local_comfyui" if stage == "render" else "local")
        k = (stage, backend)
        a = agg[k]
        a["n"] += 1
        a["cached"] += bool(r.get("cache_hit"))
        a["errors"] += bool(r.get("error"))
        a["ms"] += r.get("ms") or 0
        a["wh"] += r.get("energy_wh") or 0
        a["usd"] += r.get("cost_usd") or 0
        a["gpu_s"] += r.get("gpu_seconds") or 0

    gate = [r for r in rows() if r.get("stage") == "qa_gate"]
    lines = ["| stage | backend | runs | cache hits | errors | wall/GPU time | energy | $ |", "|---|---|---|---|---|---|---|---|"]
    tot_usd = tot_wh = 0.0
    for (stage, backend), a in sorted(agg.items()):
        t = f"{a['gpu_s']:.1f} s GPU" if a["gpu_s"] else f"{a['ms'] / 1000:.0f} s"
        energy = f"{a['wh']:.1f} Wh" if a["wh"] else "—"
        lines.append(f"| {stage} | {backend} | {a['n']} | {a['cached']} | {a['errors']} | {t} | {energy} | "
                     f"{a['usd'] + a['wh'] / 1000 * USD_PER_KWH:.4f} |")
        tot_usd += a["usd"] + a["wh"] / 1000 * USD_PER_KWH
        tot_wh += a["wh"]

    approved = json.loads((ROOT / "config" / "approved.json").read_text(encoding="utf-8"))
    n_pieces = len(approved["pieces"])
    n_assets = n_pieces * 4  # master + 3 crops
    lines += ["", f"**Total: ${tot_usd:.3f}** ({tot_wh:.0f} Wh of local GPU at ${USD_PER_KWH}/kWh + Comfy Cloud GPU seconds).",
              f"Approved pieces: {n_pieces} → {n_assets} deliverable files (master 2×, feed 1:1, story 9:16, banner 16:9).",
              f"**Cost per approved piece: ${tot_usd / n_pieces:.3f}** — this includes all the R&D: every benchmark, A/B and rejected render.",
              "", f"Quality gate: {sum(g['passed'] for g in gate)}/{len(gate)} verdicts passed across all attempts."]
    out = "\n".join(lines)
    print(out)
    (ROOT / "docs" / "costs.md").write_text("# Cost table\n\nGenerated by `pipeline/cost_table.py` from `out/runs.jsonl`.\n\n" + out + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
